project_id = "kisankusogixarejjphi"

[functions.migrate-encrypt-phones]
verify_jwt = false

[functions.check-expired-subscriptions]
verify_jwt = false

[functions.send-expiry-reminder]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false
